# Add to the end of your local dfhack.init

# Things to turn on
enable workflow
enable labormanager
enable autodump

# Butchering
autobutcher target 2 1 2 1 new
autobutcher autowatch
autobutcher unwatch CAT
autobutcher unwatch DOG
autobutcher start

# Settings
fastdwarf 1 0
seedwatch all 30
seedwatch start
repeat -time 4 -timeUnits days -command [ multicmd cleanowned x; clean all ] -name clean
